name: Feature Request
description: Suggest something new
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Before filing: check if this is already in [the roadmap](../docs/roadmap.md) or a [GitHub Discussion](https://github.com/vexorlabs/beacon/discussions).
        For large architectural changes, open a Discussion first.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the developer pain point. Focus on the problem, not your solution.
      placeholder: "When debugging a Playwright agent, I can't see what the page looked like when the agent clicked a button. I have to re-run the agent with manual screenshots added."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you solve it? Be concrete.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you thought about and why you ruled them out.

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - SDK (Python instrumentation)
        - Backend (FastAPI)
        - Frontend (React UI)
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Blocker — I can't use Beacon without this
        - High — significantly improves my workflow
        - Medium — would be nice to have
        - Low — minor improvement
    validations:
      required: true
